In [2]:
import numpy as np

In [ ]:
Basic Array Creation

In [11]:
# array
arr = np.array([1,2,4,5])
arr

array([1, 2, 4, 5])

In [17]:
# list
a = [1,2,4.8,3]
b = ["hellooo",22,44.5]
a
b

['hellooo', 22, 44.5]

In [19]:
np.array(a)

array([1. , 2. , 4.8, 3. ])

In [20]:
np.array(b)

array(['hellooo', '22', '44.5'], dtype='<U32')

In [21]:
l1 = [[23,44,56],[4,5,7],[66,8,9]]
l1

[[23, 44, 56], [4, 5, 7], [66, 8, 9]]

In [22]:
np.array(l1)

array([[23, 44, 56],
       [ 4,  5,  7],
       [66,  8,  9]])

In [45]:
Array Generation Function

SyntaxError: invalid syntax (3195740568.py, line 1)

In [30]:
arr = np.arange(1,21,3) # arange(start,end,step)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [37]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [41]:
arr = np.zeros((3,6)) # zeros(row,col)
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [47]:
arr = np.ones((4,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
arr = np.linspace(1,5,20) # linear Space between start and end linspace(start,end,space_no)
arr

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
Random Generation Function

In [55]:
np.random.rand(2)

array([0.67935751, 0.25862009])

In [60]:
np.random.randn(10) # normalization bet -3 to 3 nos will be generated

array([-0.64543248,  0.29195621,  0.17299313, -0.1788802 ,  0.50497287,
       -2.90630889,  0.76870938, -1.76175924,  0.19556503,  1.01620189])

In [63]:
np.random.randint(5) # random nos from 0 to 5 will be generated

2

In [73]:
np.random.randint(2,10) # randint(start,end)

9

In [74]:
np.random.randint(10,20,7) # randint(start,end,no)

array([17, 12, 16, 13, 19, 17, 13], dtype=int32)

In [ ]:
Array Attributes

In [80]:
arr = np.array([[23,44,55,6,66], [44,55,66,45,34]])
arr

array([[23, 44, 55,  6, 66],
       [44, 55, 66, 45, 34]])

In [82]:
# finds row and col
arr.shape

(2, 5)

In [83]:
arr.size

10

In [84]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods

In [85]:
arr

array([[23, 44, 55,  6, 66],
       [44, 55, 66, 45, 34]])

In [86]:
arr.min()

np.int64(6)

In [87]:
arr.max()

np.int64(66)

In [89]:
arr.sum() # total sum

np.int64(438)

In [93]:
# np.sum(array,axis) horizontal(row) = 1 & vertical(col) = 0
np.sum(arr,axis = 0)

array([ 67,  99, 121,  51, 100])

In [94]:
arr.mean()

np.float64(43.8)

In [96]:
arr.std() # standard Deviation

np.float64(17.8762412156471)

In [97]:
arr

array([[23, 44, 55,  6, 66],
       [44, 55, 66, 45, 34]])

In [98]:
arr.argmax()

np.int64(4)

In [99]:
arr.argmin()

np.int64(3)

In [116]:
Reshaping and Resizing

In [108]:
ar2 = np.arange(1,41)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [114]:
arr = ar2.reshape(5,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [112]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])