In [1]:
import numpy as np

In [ ]:
NUMPY INDEXING AND SLICING OF VECTORS

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[6]

np.int64(17)

In [7]:
arr[2:4]

array([13, 14])

In [8]:
arr[:7]

array([11, 12, 13, 14, 15, 16, 17])

In [9]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [14]:
sli = arr[3::2] # steps
sli

array([14, 16, 18, 20])

In [15]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
sli

array([14, 16, 18, 20])

In [ ]:
NUMPY INDEXING AND SLICING OF MATRIX

In [18]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
arr[4]

array([21, 22, 23, 24, 25])

In [24]:
arr[2,4]

np.int64(15)

In [25]:
arr[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
arr[0:2,1:3] # row:row,col:col

array([[2, 3],
       [7, 8]])

In [31]:
arr[2:4,3:5]

array([[14, 15],
       [19, 20]])

In [32]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [33]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [35]:
arr[:,3:5 ] # col

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [36]:
arr[3:5,:] # row

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
BOOLEAN INDEXING

In [38]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [46]:
arr_even = arr[bool_index]
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])