In [1]:
import numpy as np

# Array Operations

In [10]:
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a2 = np.arange(11,21)
a2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
a1 + a2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [15]:
 a1 - a2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [16]:
a1 * a2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [17]:
a1 / a2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [18]:
a1 ** a2

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

In [19]:
a2 // a1

array([11,  6,  4,  3,  3,  2,  2,  2,  2,  2])

# Broadcasting

In [21]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
a1 * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [28]:
a3 = np.arange(1,26).reshape(5,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
a3 * 8

array([[  8,  16,  24,  32,  40],
       [ 48,  56,  64,  72,  80],
       [ 88,  96, 104, 112, 120],
       [128, 136, 144, 152, 160],
       [168, 176, 184, 192, 200]])

# Deep and Shallow Copy

In [ ]:
# Shallow copy:dosen't change the original array creates new memory
# Deep copy:changes the content
# slice portion gets new memory
# but if copied content make of an array then it dosen't create new memory

In [62]:
# creating vector array
a4 = np.arange(1,21)
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
slice = a4[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [104]:
a4 # Shallow copy:dosen't change the original array creates new memory

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
a4[3:6]*10

array([40, 50, 60])

In [69]:
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
# Deep copy
b1 = a4
b1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
b1[0] = 33 # changing the content of b1 will also change content in a4
b1

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
a4

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
# but if copy createdof a4 then b1 changes will not get seen in a4
b1 = a4.copy()
b1[4] = 43
b1

array([33,  2,  3,  4, 43,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [90]:
a4 # here changes are not in a4 but b1 only

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix Operations

In [92]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [93]:
A

array([[1, 2],
       [3, 4]])

In [94]:
B

array([[5, 6],
       [7, 8]])

In [97]:
A * B # multiplication based on Indexing Location - which is not the correct way

array([[ 5, 12],
       [21, 32]])

In [ ]:
# correct ways of matrix multiplication is 1st row * 1st col ...

In [105]:
A @ B

array([[19, 22],
       [43, 50]])

In [106]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [108]:
# Transpose : rows become columns

In [109]:
A

array([[1, 2],
       [3, 4]])

In [110]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation
# Stacking Array

In [117]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [118]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [119]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [121]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting Array

In [124]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [131]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [132]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [133]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [134]:
np.vsplit(c,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]