In [9]:
import numpy as np

**Valid Sudoku**

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
print(s)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [10]:
row = np.sum(s,axis = 1) # rows sum
print(row)

[45 45 45 45 45 45 45 45 45]


In [11]:
col = np.sum(s,axis = 0) # cols sum
print(col)

[45 45 45 45 45 45 45 45 45]


In [12]:
row == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [13]:
col == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
      0 1 2 3 4 5 6 7 8
    --------------------
0 |   x x x x x x x x x
1 |   x x x x x x x x x
2 |   x x x x x x x x x
3 |   x x x x x x x x x
4 |   x x x x x x x x x
5 |   x x x x x x x x x
6 |   x x x x x x x x x
7 |   x x x x x x x x x
8 |   x x x x x x x x x

In [17]:
for i in row:
    if i == 45:
        print("Sudoku is valid for rows")
        break
    else:
        print("Sudoku is not Valid for rows")

Sudoku is valid for rows


In [16]:
for i in col:
    if i == 45:
        print("Sudoku is valid for cols")
        break
    else:
        print("Sudoku is not valid for cols")

Sudoku is valid for cols


In [11]:
s[0:3,0:3] # row,cols

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [14]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [16]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [18]:
for i in range(0,9,3): 
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


**General Questions**

In [9]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [26]:
#Get the shape of the matrix.


In [28]:
#Find the average age of students.


In [30]:
#Extract Math marks of all students.


In [32]:
#Find the highest Science mark.


In [34]:
#Get details of the student who scored more than 90 in Math.



In [37]:
#Increase Math marks of all students by 5.


In [39]:
#Find how many students are younger than 19.


In [41]:
#Calculate the average marks in each subject (column-wise mean).


In [43]:
#Get data of students who scored at least 80 in both subjects.


In [46]:
#Replace all Science marks < 75 with 0.
